### ISSUE TITLE
compilation failure

### ISSUE THREAD

**Issue by akaigoro** [dpsures/basic-akka-stream#1]
mvn compile
...
[INFO] Compiling 7 source files to d:\Git\Akka\basic-akka-stream\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /d:/Git/Akka/basic-akka-stream/src/main/java/org/streaming/app/simple/SimpleEtlTask.java:[24,83] lambda expressions are not supported in -source 1.5

**Comment by dpsures** [comment]
mapped the targeted java version to 1.8 in pom and committed the fix

**Comment by dpsures** [comment]
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building basic-stream-app 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ basic-stream-app ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ basic-stream-app ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 7 source files to F:\Learnings\intelliJ\akka\ws1\basic-stream-app\target\classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.913 s
[INFO] Finished at: 2018-04-07T19:24:37+05:30
[INFO] Final Memory: 15M/167M
[INFO] ------------------------------------------------------------------------

Process finished with exit code 0
